In [1]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier

In [7]:
df=pd.read_excel("iris-train.xlsx")

In [9]:
df.head()

   sepallength  sepalwidth  petallength  petalwidth           class
0          7.9         3.8          6.4         2.0  Iris-virginica
1          7.7         3.8          6.7         2.2  Iris-virginica
2          7.7         3.0          6.1         2.3  Iris-virginica
3          7.7         2.8          6.7         2.0  Iris-virginica
4          7.7         2.6          6.9         2.3  Iris-virginica

In [11]:
x=df.iloc[:,:-1]

In [12]:
x

     sepallength  sepalwidth  petallength  petalwidth
0            7.9         3.8          6.4         2.0
1            7.7         3.8          6.7         2.2
2            7.7         3.0          6.1         2.3
3            7.7         2.8          6.7         2.0
4            7.7         2.6          6.9         2.3
..           ...         ...          ...         ...
111          4.5         2.3          1.3         0.3
112          4.4         3.2          1.3         0.2
113          4.4         3.0          1.3         0.2
114          4.4         2.9          1.4         0.2
115          4.3         3.0          1.1         0.1

[116 rows x 4 columns]

In [15]:
y=df.iloc[:,-1]

In [16]:
y

0      Iris-virginica
1      Iris-virginica
2      Iris-virginica
3      Iris-virginica
4      Iris-virginica
            ...
111       Iris-setosa
112       Iris-setosa
113       Iris-setosa
114       Iris-setosa
115       Iris-setosa
Name: class, Length: 116, dtype: object

In [17]:
model=RandomForestClassifier()

In [18]:
model.fit(x,y)

RandomForestClassifier()

In [21]:
pedicion=model.predict([[5.43,4.5,1.5]])

D:\anaconda\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

ValueError: X has 3 features, but RandomForestClassifier is expecting 4 features as input.